# Generated by Django 2.2.4 on 2020-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='member_3_enrollment',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='member_3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
