# Generated by Django 2.2.4 on 2020-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0002_auto_20200316_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='member_2_enrollment',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
