# Generated by Django 2.2.4 on 2020-03-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0003_auto_20200316_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hod_feedback',
            field=models.CharField(default='No feedback', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor_feedback',
            field=models.CharField(default='No feedback', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='No status', max_length=500),
        ),
    ]
