# Generated by Django 2.2.4 on 2020-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0009_auto_20200325_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_message',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor_message',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
