# Generated by Django 2.2.4 on 2020-03-25 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0010_auto_20200325_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='member_1_enrollment',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='member_2_enrollment',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='member_3_enrollment',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
