# Generated by Django 2.2.4 on 2020-03-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0011_auto_20200325_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='minor.GroupInfo'),
        ),
    ]
