# Generated by Django 2.2.4 on 2020-04-24 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0016_auto_20200424_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo',
            name='contact',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(6000000000)]),
        ),
    ]
